ann_root: '../data/kvqg'
image_root: '../data/kvqg/kvqg_images/'

# set pretrained as a file path or an url
pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_vqa_capfilt_large.pth'
pre_cgmodel: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_caption_capfilt_large.pth'

# size of vit model; base or large
vit: 'base'
batch_size_train: 1
batch_size_test: 2
vit_grad_ckpt: False
vit_ckpt_layer: 0
init_lr: 2e-5

image_size: 384   
prompt: 'a picture of '

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 10

# coefficient to be added in front of the qg loss
qg_weight: 1