ann_root: '../data/textrs-300'
image_root: '/data/textrs-300/TextRS/images/'
dataset: 'textrs'

# set pretrained as a file path or an url
pretrained: 'output/TextRS-300/Model3/checkpoint_best.pth'
pre_cgmodel: ''

# size of vit model; base or large
vit: 'base'
batch_size_train: 1
batch_size_test: 2
vit_grad_ckpt: False
vit_ckpt_layer: 0
init_lr: 1e-6

image_size: 384   
prompt: 'a picture of '

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 10

# coefficient to be added in front of the qg loss
qg_weight: 1